# Generated by Django 2.2.7 on 2020-02-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
