# Generated by Django 2.2.7 on 2020-03-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='password',
        ),
    ]
