# Generated by Django 2.2.6 on 2019-10-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='publish_date',
        ),
    ]
