# Generated by Django 2.2.6 on 2019-10-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_new_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
