# Generated by Django 2.2.7 on 2020-02-28 12:42

from django.db import migrations, models
import uploaded_choices.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_choices', '0002_uploadedfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=429916160, upload_to=uploaded_choices.models.user_directory_path),
        ),
    ]
