# Generated by Django 2.2.7 on 2020-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsconf',
            name='administrator',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
