# Generated by Django 2.2.7 on 2020-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='security_room',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
