# Generated by Django 2.2.7 on 2020-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20200218_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='The IP address of this session'),
        ),
    ]
