# Generated by Django 2.2.7 on 2020-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20200226_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_time',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='when',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
