# Generated by Django 2.2.7 on 2020-02-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200221_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
